# Generated by Django 3.0.8 on 2020-07-22 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_capteur', models.CharField(max_length=30, unique=True)),
                ('adresse_capteur', models.CharField(max_length=30)),
                ('description_capteur', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone_proprio', models.CharField(blank=True, max_length=30, verbose_name='Numéro de téléphone')),
                ('avatar', models.ImageField(null=True, upload_to='avatars/', verbose_name='photo de profil')),
                ('pays_proprio', django_countries.fields.CountryField(max_length=2, verbose_name='votre pays')),
            ],
        ),
        migrations.CreateModel(
            name='Reseau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_reseau', models.CharField(max_length=30)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('description_reseau', models.TextField(max_length=500)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('duree', models.IntegerField()),
                ('cout', models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sous', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Proprietaire')),
                ('reseau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Reseau')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Puits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=15)),
                ('cle', models.CharField(max_length=32)),
                ('reseau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Reseau')),
            ],
        ),
        migrations.CreateModel(
            name='Etat_capteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energie', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Capteur')),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_ctrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_livraison', models.FloatField()),
                ('qlte_signal', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('voisin', models.TextField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Capteur')),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_appli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_brute', models.IntegerField()),
                ('valeur_traite', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Capteur')),
            ],
        ),
        migrations.AddField(
            model_name='capteur',
            name='reseau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionIoT.Reseau'),
        ),
    ]
